version: '3.8'
services:
  app:
    image: mcr.microsoft.com/vscode/devcontainers/python:3.8
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"